@include('back.layout.assets')
@include('back.layout.navbar')
@include('back.layout.column', ['title' => 'BERITA'])
@include('back.layout.footer')
@yield('content')
@yield('content')
@yield('content')
@yield('content')