@include('back.layout.assets')
@include('back.layout.navbar')
@include('back.layout.column', ['title' => 'INFO KEGIATAN'])
@include('back.layout.footer')
@yield('content')
@yield('content')
@yield('content')
@yield('content')